### ISSUE TITLE
Ontologizer Dependencies

### ISSUE THREAD

**Issue by stuppie** [drseb/boqa#3]
Hello, if you could assist me with getting your project to build it would be greatly appreciated. I'm having trouble locating the correct ontologizer dependencies. I see the [ontologizerlib](https://github.com/ontologizer/ontologizerlib) repo, but it does not contain many things that this project is looking for, for example `ontologizer.association.AssociationParser`, `ontologizer.go.OBOParser`, and I can't figure out where they are. Could you point me to them? Thanks

**Comment by stuppie** [comment]
Ok, I managed to find this repo: https://github.com/phenotips/ontologizer
Its still missing `ontologizer.association.AssociationParser.Type` however..
And many methods are inconsistent. It has `oboParser.getFormatVersion()` but is missing `oboParser.getDataVersion()`, for example.

**Comment by iamkoehler** [comment]
add this to your pom may work: 

```
<!-- <dependency> -->
		<!-- <groupId>ontologizer</groupId> -->
		<!-- <artifactId>ontologizer</artifactId> -->
		<!-- <version>0.0.3-SNAPSHOT</version> -->
		<!-- </dependency> -->
```

and
```

<repositories>
		<repository>
			<id>compbio</id>
			<url>http://compbio.charite.de/tl_files/maven</url>
		</repository>
	</repositories>
```

the code of this ontologizer-fork is here: https://github.com/drseb/ontologizer
